ERROR: 'dict' object is not callable
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 142, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 86, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    controls = motors(manual=1,init_time=init_time,logfile=logfile,cam=cam,demo=demo)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 84, in __init__
    self.manual_setup()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 121, in manual_setup
    self.video_update()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 88, in video_update
    print(self.instruction('FORWARD'))
TypeError: 'dict' object is not callable

Ran for 1.08 seconds.

ERROR: 'remote_gpio' object has no attribute 'IN'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 156, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 94, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 35, in main
    controls = motors(manual=1,init_time=init_time,logfile=logfile,cam=cam,demo=demo)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 95, in __init__
    io.setup(self.pins[8],io.IN,pull_up_down=io.PUD_DOWN)
AttributeError: 'remote_gpio' object has no attribute 'IN'

Ran for 0.73 seconds.

ERROR: 'remote_gpio' object has no attribute 'IN'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 156, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 94, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 35, in main
    controls = motors(manual=1,init_time=init_time,logfile=logfile,cam=cam,demo=demo)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 95, in __init__
    io.setup(self.pins[8],io.IN,pull_up_down=io.PUD_DOWN)
AttributeError: 'remote_gpio' object has no attribute 'IN'

Ran for 0.72 seconds.

ERROR: FSM.__init__() takes 7 positional arguments but 8 were given
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 156, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 94, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 36, in main
    fsm = FSM(controls,noprint,cam,demo,init_time,logfile,gettimes)
TypeError: FSM.__init__() takes 7 positional arguments but 8 were given

Ran for 11.83 seconds.

ERROR: FSM.__init__() takes 7 positional arguments but 8 were given
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 156, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 94, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 36, in main
    fsm = FSM(controls,noprint,cam,demo,init_time,logfile,gettimes)
TypeError: FSM.__init__() takes 7 positional arguments but 8 were given

Ran for 3.32 seconds.

ERROR: 
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 156, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 94, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 35, in main
    controls = motors(manual=1,init_time=init_time,logfile=logfile,cam=cam,demo=demo)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 121, in __init__
    self.manual_setup()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 157, in manual_setup
    self.video_update()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 125, in video_update
    self.cam.update_goal_position('ball',time.time(),manual=self.manual_mode)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 30, in update_goal_position
    position_xy,image = self.camera_.getimage() #torch.randint(0,255,(1280,720)) # Get image from camera
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 209, in getimage
    if not self.q.empty():
  File "/home/ldavila2/miniconda3/lib/python3.10/queue.py", line 109, in empty
    return not self._qsize()
  File "/home/ldavila2/miniconda3/lib/python3.10/queue.py", line 209, in _qsize
    def _qsize(self):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 371, in signal_handler
    raise TimeoutError
TimeoutError

Ran for 25.33 seconds.

ERROR: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 153, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 91, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 46, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 74, in wait
    timers = self.img.update_goal_position('ball',time.time())
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 41, in update_goal_position
    self.camera_.show_tracking(image,position_xy,manual)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 234, in show_tracking
    height, width = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Ran for 38.32 seconds.

ERROR: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 153, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 91, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 46, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 74, in wait
    timers = self.img.update_goal_position('ball',time.time())
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 41, in update_goal_position
    self.camera_.show_tracking(image,position_xy,manual)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 234, in show_tracking
    height, width = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Ran for 32.02 seconds.

Time: 18.10.28
ERROR: StateLogic.__init__() takes from 1 to 8 positional arguments but 9 were given
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 87, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 57, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 28, in main
    fsm = FSM(controls,cam,gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 332, in __init__
    super().__init__(controls,camera,gettimes,noprint,demo,manual,init_time,logfile)
TypeError: StateLogic.__init__() takes from 1 to 8 positional arguments but 9 were given

Ran for 5.53 seconds.

Time: 18.30.04
ERROR: images.__init__() missing 1 required positional argument: 'manual'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 87, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 57, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 26, in main
    cam = camera(demo,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 93, in __init__
    super().__init__(self,demo)
TypeError: images.__init__() missing 1 required positional argument: 'manual'

Ran for 0.70 seconds.

Time: 18.33.57
ERROR: images.update_goal_position() got an unexpected keyword argument 'manual'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 87, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 57, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 27, in main
    controls = motors(manual=manual,init_time=init_time,logfile=logfile,cam=cam,demo=demo)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 120, in __init__
    self.manual_setup()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 156, in manual_setup
    self.video_update()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 124, in video_update
    self.cam.update_goal_position('ball',time.time(),manual=self.manual)
TypeError: images.update_goal_position() got an unexpected keyword argument 'manual'

Ran for 1.06 seconds.

Time: 18.38.42
ERROR: 'FSM' object has no attribute 'img'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 87, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 57, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 38, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 40, in wait
    timers = self.img.update_goal_position('ball',time.time())
AttributeError: 'FSM' object has no attribute 'img'

Ran for 7.14 seconds.

Time: 18.46.04
ERROR: 'FSM' object has no attribute 'img'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 88, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 40, in wait
    timers = self.img.update_goal_position('ball',time.time())
AttributeError: 'FSM' object has no attribute 'img'

Ran for 5.73 seconds.

Time: 18.47.08
ERROR: 'FSM' object has no attribute 'img'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 88, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 40, in wait
    timers = self.img.update_goal_position('ball',time.time())
AttributeError: 'FSM' object has no attribute 'img'

Ran for 32.84 seconds.

Time: 18.47.18
ERROR: 'FSM' object has no attribute 'img'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 88, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 40, in wait
    timers = self.img.update_goal_position('ball',time.time())
AttributeError: 'FSM' object has no attribute 'img'

Ran for 5.82 seconds.

Time: 18.48.11
ERROR: 'FSM' object has no attribute 'img'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 88, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 40, in wait
    timers = self.img.update_goal_position('ball',time.time())
AttributeError: 'FSM' object has no attribute 'img'

Ran for 23.31 seconds.

Time: 18.48.56
ERROR: 'FSM' object has no attribute 'img'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 88, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 40, in wait
    timers = self.img.update_goal_position('ball',time.time())
AttributeError: 'FSM' object has no attribute 'img'

Ran for 38.79 seconds.

Time: 18.50.25
ERROR: 'FSM' object has no attribute 'img'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 88, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 40, in wait
    timers = self.img.update_goal_position('ball',time.time())
AttributeError: 'FSM' object has no attribute 'img'

Ran for 14.55 seconds.

Time: 18.55.11
ERROR: 'FSM' object has no attribute 'controls'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 89, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 15, in main
    fsm = FSM(controls,cam,gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 339, in __init__
    super().__init__(controls,camera,gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 20, in __init__
    self.manual_off()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 314, in manual_off
    self.controls.manual=0
AttributeError: 'FSM' object has no attribute 'controls'

Ran for 22.96 seconds.

Time: 19.00.19
ERROR: name 'controls' is not defined
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 89, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 15, in main
    fsm = FSM(controls,cam,gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 343, in __init__
    super().__init__(controls,camera,gettimes,noprint,demo,manual,init_time,logfile)
NameError: name 'controls' is not defined

Ran for 6.66 seconds.

Time: 19.06.02
ERROR: list index out of range
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 89, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 14, in main
    controls  = motors(cam,gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 97, in __init__
    io.setup(self.pins[8],io.IN,pull_up_down=io.PUD_DOWN)
IndexError: list index out of range

Ran for 0.71 seconds.

Time: 19.06.34
ERROR: name 'controls' is not defined
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 89, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 44, in main_fetching
    main(args[:4],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 15, in main
    fsm = FSM(controls,cam,gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 343, in __init__
    super().__init__(controls,camera,gettimes,noprint,demo,manual,init_time,logfile)
NameError: name 'controls' is not defined

Ran for 11.60 seconds.

Time: 20.11.41
ERROR: 'cv2.VideoCapture' object has no attribute 'destroy'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 97, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 45, in main_fetching
    main(gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 24, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 41, in wait
    timers = self.img.update_goal_position('ball',time.time())
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 28, in update_goal_position
    position_xy,image = self.camera_.getimage()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 199, in getimage
    if not self.q.empty():
  File "/home/ldavila2/miniconda3/lib/python3.10/queue.py", line 108, in empty
    with self.mutex:
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 58, in signal_handler
    fsm.img.cam.destroy()
AttributeError: 'cv2.VideoCapture' object has no attribute 'destroy'

Ran for 3.96 seconds.

Time: 21.06.00 (manually added error entry)
Exception ignored in: <module 'threading' from '/home/ldavila2/miniconda3/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/home/ldavila2/miniconda3/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
FATAL: exception not rethrown
Aborted (core dumped)

Time: 21.14.10
ERROR: list index out of range
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 109, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 56, in main_fetching
    main(gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 13, in main
    ctrl = control(cam,gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 97, in __init__
    io.setup(self.pins[8],io.IN,pull_up_down=io.PUD_DOWN)
IndexError: list index out of range

Ran for 0.71 seconds.

Time: 21.40.44
ERROR: 'camera' object has no attribute 'logfile'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 109, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 56, in main_fetching
    main(gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 12, in main
    cam   = camera(             noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/camera.py", line 70, in __init__
    writefile(self.logfile,"Initializing camera...  ")
AttributeError: 'camera' object has no attribute 'logfile'

Ran for 0.00 seconds.

Time: 21.41.37
ERROR: type object 'remote_gpio' has no attribute 'BCM'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 109, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 56, in main_fetching
    main(gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 13, in main
    ctrl = control(cam,gettimes,noprint,demo,manual,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 49, in __init__
    io.setmode(io.BCM)
AttributeError: type object 'remote_gpio' has no attribute 'BCM'

Ran for 0.71 seconds.

Time: 21.53.09
ERROR: name 'args' is not defined
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 109, in <module>
    main_fetching(args,init_time,logfile)
NameError: name 'args' is not defined

Ran for 0.00 seconds.

Time: 21.53.28
ERROR: invalid literal for int() with base 10: 'time'
Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 108, in <module>
    args = [None,int(argv[0]),1,int(argv[1])]
ValueError: invalid literal for int() with base 10: 'time'

Ran for 0.00 seconds.

