ERROR: 'camera' object has no attribute 'timer'

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 139, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 82, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 35, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 73, in wait
    if self.img.timer>=5: # NOTE: software simulation/testing change2 in self.img.regions.values():
AttributeError: 'camera' object has no attribute 'timer'

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 138, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 81, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 51, in main
    fsm.ret()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 141, in ret
    self.img.update_goal_position('waitpoint')
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 37, in update_goal_position
    position_xy,image = self.camera_.getimage() #torch.randint(0,255,(1280,720)) # Get image from camera
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 216, in getimage
    if not self.q.empty():
  File "/home/ldavila2/miniconda3/lib/python3.10/queue.py", line 109, in empty
    return not self._qsize()
  File "/home/ldavila2/miniconda3/lib/python3.10/queue.py", line 209, in _qsize
    def _qsize(self):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 375, in signal_handler
    raise TimeoutError
TimeoutError

ERROR: 'motors' object has no attribute 'update_goal_position'

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 138, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 81, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    controls = motors(manual=1,init_time=init_time,logfile=logfile,cam=cam,demo=demo)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 66, in __init__
    self.manual_setup()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 94, in manual_setup
    self.video_update()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 69, in video_update
    self.update_goal_position('ball',time.time())
AttributeError: 'motors' object has no attribute 'update_goal_position'

ERROR: 'camera' object has no attribute 'release'

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 138, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 81, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    controls = motors(manual=1,init_time=init_time,logfile=logfile,cam=cam,demo=demo)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 66, in __init__
    self.manual_setup()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 97, in manual_setup
    self.cam.release()
AttributeError: 'camera' object has no attribute 'release'

ERROR: 'NoneType' object has no attribute 'shape'

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 138, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 81, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 34, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 66, in wait
    timers = self.img.update_goal_position('ball',time.time())
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 48, in update_goal_position
    self.camera_.show_tracking(image,position_xy)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 240, in show_tracking
    height, width = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

ERROR: 'NoneType' object has no attribute 'shape'

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 138, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 81, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 34, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 66, in wait
    timers = self.img.update_goal_position('ball',time.time())
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 48, in update_goal_position
    self.camera_.show_tracking(image,position_xy,manual)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 240, in show_tracking
    height, width = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

ERROR: 'NoneType' object has no attribute 'shape'

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 138, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 81, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 34, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 66, in wait
    timers = self.img.update_goal_position('ball',time.time())
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 48, in update_goal_position
    self.camera_.show_tracking(image,position_xy,manual)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 240, in show_tracking
    height, width = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

ERROR: can't invoke "destroy" command: application has been destroyed

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 138, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 81, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 25, in main
    controls = motors(manual=1,init_time=init_time,logfile=logfile,cam=cam,demo=demo)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 67, in __init__
    self.manual_setup()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 97, in manual_setup
    self.exit_()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 276, in exit_
    self.root.destroy()
  File "/home/ldavila2/miniconda3/lib/python3.10/tkinter/__init__.py", line 2341, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed

ERROR: '_tkinter.tkapp' object has no attribute 'exit_'

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 68, in __init__
    self.manual_setup()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 99, in manual_setup
    self.root.mainloop()
  File "/home/ldavila2/miniconda3/lib/python3.10/tkinter/__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 143, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 86, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 30, in main
    controls = motors(manual=1,init_time=init_time,logfile=logfile,cam=cam,demo=demo)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/gpio.py", line 70, in __init__
    self.root.exit_()
  File "/home/ldavila2/miniconda3/lib/python3.10/tkinter/__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'exit_'

ERROR: Replacement index 1 out of range for positional args tuple

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 138, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 81, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 34, in main
    next_function_index = fsm.wait()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 75, in wait
    writefile(self.logfile,"\n{} - Final region data: {}\n".format(list(self.img.regions.values())))
IndexError: Replacement index 1 out of range for positional args tuple

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 138, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 81, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 51, in main
    fsm.ret()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 138, in ret
    self.img.update_goal_position('waitpoint')
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 30, in update_goal_position
    position_xy,image = self.camera_.getimage() #torch.randint(0,255,(1280,720)) # Get image from camera
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/img_proc.py", line 209, in getimage
    if not self.q.empty():
  File "/home/ldavila2/miniconda3/lib/python3.10/queue.py", line 109, in empty
    return not self._qsize()
  File "/home/ldavila2/miniconda3/lib/python3.10/queue.py", line 209, in _qsize
    def _qsize(self):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/state_machine.py", line 363, in signal_handler
    raise TimeoutError
TimeoutError

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 141, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 84, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 53, in main
    fsm.transition_return()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/pystatemachine.py", line 125, in transition
    raise InvalidStateTransition()
pystatemachine.InvalidStateTransition

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 141, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 84, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 53, in main
    fsm.transition_return()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/pystatemachine.py", line 125, in transition
    raise InvalidStateTransition()
pystatemachine.InvalidStateTransition

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 141, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 84, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 53, in main
    fsm.transition_return()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/pystatemachine.py", line 125, in transition
    raise InvalidStateTransition()
pystatemachine.InvalidStateTransition

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 141, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 84, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 53, in main
    fsm.transition_return()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/pystatemachine.py", line 125, in transition
    raise InvalidStateTransition()
pystatemachine.InvalidStateTransition

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 141, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 84, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 53, in main
    fsm.transition_return()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/pystatemachine.py", line 125, in transition
    raise InvalidStateTransition()
pystatemachine.InvalidStateTransition

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 143, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 86, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 53, in main
    fsm.transition_return()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/pystatemachine.py", line 125, in transition
    raise InvalidStateTransition()
pystatemachine.InvalidStateTransition

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 143, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 86, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 53, in main
    fsm.transition_return()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/pystatemachine.py", line 125, in transition
    raise InvalidStateTransition()
pystatemachine.InvalidStateTransition

ERROR: 

Traceback (most recent call last):
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 143, in <module>
    main_fetching(args,init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 86, in main_fetching
    main(args[:3],init_time,logfile)
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/main.py", line 53, in main
    fsm.transition_return()
  File "/home/ldavila2/445/sp2023-445/notebooks/luis/code/pystatemachine.py", line 125, in transition
    raise InvalidStateTransition()
pystatemachine.InvalidStateTransition

